In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import spacy
nlp = spacy.load('en')

import urllib.request
import urllib.parse

from bs4 import BeautifulSoup

In [7]:
def prepare_sequence(seq, to_ix):
    idxs = [to_ix[w] for w in seq]
    return torch.tensor(idxs, dtype=torch.long)

In [8]:
def prepare_lable(size,lable):
    temp = []
    for i in range(size -1):
        temp += [0]   
    if lable == 1:
        temp += [1]
    else:
        temp += [0]
    
    return torch.tensor(temp, dtype=torch.long)

In [9]:
def get_pos(sentence):
    temp=[]
    doc = nlp(sentence)
    for i in range(len(doc)):
        #temp += [doc[i].tag_]
        temp += [doc[i].pos_]
    return temp

In [56]:
abstr_id = 30252254
train = ''
for i in range(100):
    url = 'https://www.ncbi.nlm.nih.gov/pubmed/'+str(abstr_id)
    html = urllib.request.urlopen(url)
    parsed_html = BeautifulSoup(html)
    if parsed_html is not None:
        train += parsed_html.body.find('div', attrs={'class':'abstr'}).find('p').text 
    #train += '.'
    abstr_id+=1
print(train)
#print(x.read())

/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


Cockayne syndrome, first described in 1936 by Dr. Cockayne, is a rare genetic disorder, mainly characterized by growth disorders, intellectual deficit, neuromotor difficulties, and impaired vision and hearing. The children look cachectic with a prematurely aged face. There are different types of the syndrome. They depend on the age at which the disease manifests itself and the severity of the manifestations: Type 1 is also called "classical form." It usually occurs at 1 year of age by stunting and neurological disorders, followed by a decline in vision and hearing. Type 2 is a severe form of the syndrome. Neurological disorders and some ocular abnormalities are present from the outset at birth. Type 3 corresponds to a moderate form. There are 2 other rare, special forms of Cockayne syndrome.[1][2][3]Hemarthrosis is bleeding into a joint cavity. Its presence can be suspected based upon patient history, physical exam, and multiple imaging modalities; however, the best way to diagnose hem

In [79]:
train_sentence = train.split('.',train.count('.'))
counter = 0
print("train_sentence : " + str(len(train_sentence)))
print("--------------------------------------------------------------------------------------")
for p in train_sentence:
    if p is "":
        train_sentence.remove("")
    else:
        print("index : "+str(counter))
        counter+=1
        print (p)
        print("--------------------------------------------------------------------------------------")

train_sentence : 920
--------------------------------------------------------------------------------------
index : 0
Cockayne syndrome, first described in 1936 by Dr
--------------------------------------------------------------------------------------
index : 1
 Cockayne, is a rare genetic disorder, mainly characterized by growth disorders, intellectual deficit, neuromotor difficulties, and impaired vision and hearing
--------------------------------------------------------------------------------------
index : 2
 The children look cachectic with a prematurely aged face
--------------------------------------------------------------------------------------
index : 3
 There are different types of the syndrome
--------------------------------------------------------------------------------------
index : 4
 They depend on the age at which the disease manifests itself and the severity of the manifestations: Type 1 is also called "classical form
--------------------------------------------

--------------------------------------------------------------------------------------
index : 589
 The tendon then inserts on the medial aspect of the proximal phalanx of the thumb as well as the extensor hood
--------------------------------------------------------------------------------------
index : 590
Le Fort injuries are complex fractures of the midface, named after Rene Le Fort who studied cadaver skulls that were subjected to blunt force trauma
--------------------------------------------------------------------------------------
index : 591
 His experiments determined the areas of structural weakness of the maxilla designated as “lines of weakness” where fractures occurred
--------------------------------------------------------------------------------------
index : 592
 These fractures are classified into 3 distinct groups based on the direction of the fracture: horizontal, pyramidal or transverse
-----------------------------------------------------------------------------

In [83]:
#for 20
# train_target = [1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
#                 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
train_target=[]

for i in range(len(train_sentence)):
    train_target += [1]
need_to_change=[0,1,4,5,30,31,32,33,34,50,51,52,53,54,55,56,57,58,59,60,61,62,100,101,103,104,129,130,131,132,133,161,162,163,165,166,174,175
               ,187,188,189,190,201,202,209,210,216,217,266,267,290,294,297,383,384,463,464,466,467,468,469,470,471,472,542,544,546,548,550
               ,622,623,680,681,682,731,732,733,734,735,736,737,738,740,741,828,829,830,831,833,834,856,857]
for i in need_to_change:
    train_target[i] = 0
print(train_target)

[0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [97]:
training_data=[]
for i in range(len(train_sentence)):
    training_data+=[ (get_pos(train_sentence[i]), train_target[i]) ]
print(training_data)

[(['PROPN', 'NOUN', 'PUNCT', 'ADV', 'VERB', 'ADP', 'NUM', 'ADP', 'PROPN'], 0), (['SPACE', 'PROPN', 'PUNCT', 'VERB', 'DET', 'ADJ', 'ADJ', 'NOUN', 'PUNCT', 'ADV', 'VERB', 'ADP', 'NOUN', 'NOUN', 'PUNCT', 'ADJ', 'NOUN', 'PUNCT', 'NOUN', 'NOUN', 'PUNCT', 'CCONJ', 'ADJ', 'NOUN', 'CCONJ', 'NOUN'], 0), (['SPACE', 'DET', 'NOUN', 'VERB', 'ADJ', 'ADP', 'DET', 'ADV', 'ADJ', 'NOUN'], 1), (['SPACE', 'ADV', 'VERB', 'ADJ', 'NOUN', 'ADP', 'SPACE', 'DET', 'NOUN'], 1), (['SPACE', 'PRON', 'VERB', 'ADP', 'DET', 'NOUN', 'ADP', 'ADJ', 'DET', 'NOUN', 'VERB', 'PRON', 'CCONJ', 'DET', 'NOUN', 'ADP', 'DET', 'NOUN', 'PUNCT', 'NOUN', 'NUM', 'VERB', 'ADV', 'VERB', 'PUNCT', 'ADJ', 'NOUN'], 0), (['PUNCT', 'PRON', 'ADV', 'VERB', 'ADP', 'NUM', 'NOUN', 'ADP', 'NOUN', 'ADP', 'VERB', 'CCONJ', 'ADJ', 'NOUN', 'PUNCT', 'VERB', 'ADP', 'DET', 'NOUN', 'ADP', 'NOUN', 'CCONJ', 'NOUN'], 0), (['SPACE', 'NOUN', 'NUM', 'VERB', 'DET', 'ADJ', 'NOUN', 'ADP', 'DET', 'NOUN'], 1), (['SPACE', 'ADJ', 'NOUN', 'CCONJ', 'DET', 'ADJ', 'NOUN', 'VE

In [85]:
# import csv
# training_data=[]
# with open('data/test4.csv', newline='') as csvfile:
#     rows = csv.reader(csvfile)
#     for row in rows:
#         training_data+=[ (get_pos(row[0]), int(row[1])) ]
   
# print(len(training_data))
# print(training_data)

In [86]:
# word_to_ix = {}
# for sent, tags in training_data:
#     for word in sent:
#         if word not in word_to_ix:
#             word_to_ix[word] = len(word_to_ix)
# print(word_to_ix)
word_to_ix = {'SPACE': 0, 'ADP':1, 'ADV':2, 'AUX':3, 'CONJ':4, 'CCONJ':5, 'DET':6, 'INTJ':7, 'NUM':8, 'PART':9, 'PRON':10,
              'PROPN':11, 'PUNCT':12, 'SCONJ':13, 'SYM':14, 'VERB':15, 'NOUN':16, 'X':17, 'ADJ': 18 }

print(prepare_sequence(training_data[0][0], word_to_ix))
print(prepare_lable(len(training_data[0][0]),training_data[0][1]))
print(prepare_sequence(training_data[1][0], word_to_ix))
print(prepare_lable(len(training_data[1][0]),training_data[1][1]))

tensor([11, 16, 12,  2, 15,  1,  8,  1, 11])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([ 0, 11, 12, 15,  6, 18, 18, 16, 12,  2, 15,  1, 16, 16, 12, 18, 16, 12,
        16, 16, 12,  5, 18, 16,  5, 16])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])


In [87]:
class LSTMTagger(nn.Module):

    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim

        self.word_embeddings = nn.Embedding(vocab_size, embedding_dim)

        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.lstm = nn.LSTM(embedding_dim, hidden_dim)

        # The linear layer that maps from hidden state space to tag space
        self.hidden2tag = nn.Linear(hidden_dim, tagset_size)
        self.hidden = self.init_hidden()

    def init_hidden(self):
        # Before we've done anything, we dont have any hidden state.
        # Refer to the Pytorch documentation to see exactly
        # why they have this dimensionality.
        # The axes semantics are (num_layers, minibatch_size, hidden_dim)
        return (torch.zeros(1, 1, self.hidden_dim),
                torch.zeros(1, 1, self.hidden_dim))

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm( embeds.view(len(sentence), 1, -1), self.hidden)
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space,dim=1)
        #tag_scores = torch.sigmoid(tag_scores)
        return tag_scores

In [98]:
EMBEDDING_DIM = 6
HIDDEN_DIM = 6

model = LSTMTagger(EMBEDDING_DIM, HIDDEN_DIM, len(word_to_ix), 2)
loss_function = nn.NLLLoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

for epoch in range(50):  # again, normally you would NOT do 300 epochs, it is toy data
    for sentence, lable in training_data:
        # Step 1. Remember that Pytorch accumulates gradients.
        # We need to clear them out before each instance
        model.zero_grad()

        # Also, we need to clear out the hidden state of the LSTM,
        # detaching it from its history on the last instance.
        model.hidden = model.init_hidden()

        # Step 2. Get our inputs ready for the network, that is, turn them into
        # Tensors of word indices.
        sentence_in = prepare_sequence(sentence, word_to_ix)
        targets = prepare_lable(len(sentence),lable)
        
        # Step 3. Run our forward pass.
        tag_scores = model(sentence_in)

        # Step 4. Compute the loss, gradients, and update the parameters by
        #  calling optimizer.step()
        loss = loss_function(tag_scores, targets)
        loss.backward()
        optimizer.step()
        
    #print(epoch)
    

In [138]:
import numpy as np
def get_consequence(output):
    x = output.data.numpy()[-1,0]
    y = output.data.numpy()[-1,1]
    
    if x < y :
        print(x,y)
        print("yes(100%)")
    else:
        print(x,y)
        if y > -5:
            print("yes(50%)")
        else:
            print("not")

In [139]:
inputs = prepare_sequence(get_pos("It is an apple"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)
print(tag_scores)

-0.29890352 -1.3533664
yes(50%)
tensor([[-0.0017, -6.3696],
        [-0.0071, -4.9564],
        [-0.0035, -5.6452],
        [-0.2989, -1.3534]], grad_fn=<LogSoftmaxBackward>)


In [146]:
inputs = prepare_sequence(get_pos("The children look cachectic with a prematurely aged face. There are different types of the syndrome"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)

-0.29890352 -1.3533664
yes(50%)


In [147]:
inputs = prepare_sequence(get_pos("Cockayne syndrome, first described in 1936 by Dr"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)

-0.0035955906 -5.629863
not


In [166]:
inputs = prepare_sequence(get_pos("Primary renal lymphoma comprises only 0"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)

-0.0035409927 -5.645155
not


In [165]:
inputs = prepare_sequence(get_pos("Ibuprofen, 2-(4-isobutylphenyl)propionic acid, belonging to the class of drugs called nonsteroidal anti-inflammatory drugs (NSAIDs) was discovered by Dr"), word_to_ix)
tag_scores = model(inputs)
get_consequence(tag_scores)

-0.0035881996 -5.6319036
not


In [152]:
# file = open('data/text.txt')
# text = file.read()
# print(text)

In [171]:
abstr_id = 30252110
test=''
j=0
for j in range(2):
    url = 'https://www.ncbi.nlm.nih.gov/pubmed/'+str(abstr_id)
    html = urllib.request.urlopen(url)
    parsed_html = BeautifulSoup(html)
    if parsed_html is not None:
        test += parsed_html.body.find('div', attrs={'class':'abstr'}).find('p').text
    abstr_id+=1
print(test)

/anaconda3/lib/python3.6/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 193 of the file /anaconda3/lib/python3.6/runpy.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup(YOUR_MARKUP})

to this:

 BeautifulSoup(YOUR_MARKUP, "lxml")

  markup_type=markup_type))


Uncertainty in the estimation of daytime ecosystem carbon cycling due to the light inhibition of leaf respiration and photorespiration, and how these small fluxes vary through the growing season in the field, remains a confounding element in calculations of gross primary productivity and ecosystem respiration. Our study focuses on how phenology, short-term temperature changes and canopy position influence leaf-level carbon exchange in Quercus rubra L. (red oak) at Harvard Forest in central Massachusetts, USA. Using leaf measurements and eddy covariance, we also quantify the effect of light inhibition on estimates of daytime respiration at leaf and ecosystem scales. Measured rates of leaf respiration in the light and dark were highest in the early growing season and declined in response to 10-day prior air temperatures (P < 0.01), evidence of within-season thermal acclimation. Leaf respiration was significantly inhibited by light (27.1 ± 2.82% inhibited across all measurements), and thi

In [172]:
test_sentence = test.split(".",test.count('.'))
for p in test_sentence:
    if p is "":
        test_sentence.remove("")
    else:
        print(p)

Uncertainty in the estimation of daytime ecosystem carbon cycling due to the light inhibition of leaf respiration and photorespiration, and how these small fluxes vary through the growing season in the field, remains a confounding element in calculations of gross primary productivity and ecosystem respiration
 Our study focuses on how phenology, short-term temperature changes and canopy position influence leaf-level carbon exchange in Quercus rubra L
 (red oak) at Harvard Forest in central Massachusetts, USA
 Using leaf measurements and eddy covariance, we also quantify the effect of light inhibition on estimates of daytime respiration at leaf and ecosystem scales
 Measured rates of leaf respiration in the light and dark were highest in the early growing season and declined in response to 10-day prior air temperatures (P < 0
01), evidence of within-season thermal acclimation
 Leaf respiration was significantly inhibited by light (27
1 ± 2
82% inhibited across all measurements), and thi

In [173]:
for t in test_sentence:
    print(t)
    #print(get_pos(t))
    inputs = prepare_sequence(get_pos(t), word_to_ix)
    tag_scores = model(inputs)
    print(inputs)
    get_consequence(tag_scores)
    print("--------------------------------------------------------")

Uncertainty in the estimation of daytime ecosystem carbon cycling due to the light inhibition of leaf respiration and photorespiration, and how these small fluxes vary through the growing season in the field, remains a confounding element in calculations of gross primary productivity and ecosystem respiration
tensor([16,  1,  6, 16,  1, 18, 16, 16, 16,  1,  1,  6, 18, 16,  1, 16, 16,  5,
        16, 12,  5,  2,  6, 18, 16, 15,  1,  6, 15, 16,  1,  6, 16, 12, 15,  6,
        15, 16,  1, 16,  1, 18, 18, 16,  5, 16, 16])
-0.29890352 -1.3533664
yes(50%)
--------------------------------------------------------
 Our study focuses on how phenology, short-term temperature changes and canopy position influence leaf-level carbon exchange in Quercus rubra L
tensor([ 0, 18, 16, 15,  1,  2, 16, 12, 18, 12, 16, 16, 16,  5, 16, 16, 16, 16,
        12, 16, 16, 16,  1, 11, 16, 16])
-0.29890352 -1.3533664
yes(50%)
--------------------------------------------------------
 (red oak) at Harvard Forest in c